name: CD

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  push:
    branches: [ "master" ]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      # Run all pre-commit hooks on all the files.
      - name: Install and Run Pre-commit
        uses: pre-commit/action@v2.0.0

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Build instance
        run:  docker-compose -f local.yml up -d --build

      - name: Run Django Tests
        run:  docker-compose -f local.yml run --rm django pytest

      - name: Tear down the Stack
        run:  docker-compose -f local.yml down

  # Deploy to production
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [ "linter", "test" ]
  #   steps:
  #     - name: Checkout Code Repository
  #       uses: actions/checkout@v2

  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ${{ secrets.AWS_REGION }}

  #     - name: Generate deployment package
  #       run: zip -r deploy.zip . -x '*.git*'

  #     - name: Deploy to EB
  #       uses: einaregilsson/beanstalk-deploy@v17
  #       with:
  #         aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         application_name: ${{ secrets.AWS_EB_APPLICATIONS }}
  #         environment_name: production
  #         version_label: ${{ github.SHA }}
  #         region: ${{ secrets.AWS_REGION }}
  #         wait_for_deployment: false
  #         deployment_package: deploy.zip
  #         use_existing_version_if_available: true
