name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: [ "master", "staging", "development" ]


jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Set up Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

  create-release:
    runs-on: ubuntu-latest
    needs: [ "linter" ]
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2
      
      - name: Get Version
        id: get-version
        run: echo "::set-output name=version::$(echo $(node -p -e "require('./package.json').version"))"

      - name: Compare versions
        run: echo ${GITHUB_REF##*/} && echo ${{ steps.get-version.outputs.version }}
