name: CD

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  PACKAGE_VERSION: "$(echo $(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]'))"

on:
  push:
    branches: [ "master" ]


jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Set up Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

  publish-npm:
    runs-on: ubuntu-latest
    needs: [ "linter" ]
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Publish update
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

  create-release:
    runs-on: ubuntu-latest
    needs: [ "linter" ]
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Test PACKAGE_VERSION
        run: echo ${{ env.PACKAGE_VERSION }}

      - name: Create release
        uses: actions/create-release@v1
        with:
          draft: false
          prerelease: false
          release_name: ${{ env.PACKAGE_VERSION }}
          tag_name: ${{ env.PACKAGE_VERSION }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
