name: CD

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  push:
    branches: [ "master" ]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Set up Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

  publish-npm:
    runs-on: ubuntu-latest
    needs: [ "linter" ]
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Publish update
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

  create-release:
    runs-on: ubuntu-latest
    needs: [ "linter" ]
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Get Latest Released Version
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      
      - name: Get New Release Version
        id: get-version
        run: echo "::set-output name=version::$(echo $(node -p -e "require('./package.json').version"))"

      - name: Create release
        if: ${{ steps.previoustag.outputs.tag != steps.get-version.outputs.version }}
        uses: actions/create-release@v1
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.get-version.outputs.version }}
          tag_name: ${{ steps.get-version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
